FROM mariadb:10.3

ENV MYSQL_DATABASE=default_database
ENV MYSQL_ROOT_PASSWORD=mypass
ENV MYSQL_USER=varun
ENV MYSQL_PASSWORD=admin

# DO NOT USE THIS Dockerfile.
# It is incomplete and very time consuming to set up correctly.
# See MariaDB_README.md for alternate way.
